DROP DATABASE IF EXISTS AULA_FUNCOES;
CREATE DATABASE AULA_FUNCOES; 
USE AULA_FUNCOES; 

CREATE TABLE FUNCIONARIO( 
ID INT NOT NULL AUTO_INCREMENT 
,NOME VARCHAR(100) NOT NULL 
,CPF CHAR(14) NOT NULL UNIQUE
,SALARIO DECIMAL(9,2) NOT NULL
,NASCIMENTO DATE NOT NULL 
,STATUS CHAR(1) NOT NULL DEFAULT 'A'
,CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID)
);

INSERT INTO FUNCIONARIO (NOME,CPF,SALARIO,NASCIMENTO,STATUS) VALUES ('ROBERTO','789.456.135-87',2500,'2000-10-22','A');
INSERT INTO FUNCIONARIO (NOME,CPF,SALARIO,NASCIMENTO,STATUS) VALUES ('RÚBIA','951.357.987-88',4261.70,'1992-07-18','I');
INSERT INTO FUNCIONARIO (NOME,CPF,SALARIO,NASCIMENTO,STATUS) VALUES ('MARCO','753.951.744-56',1800,'2002-5-01','A');
INSERT INTO FUNCIONARIO (NOME,CPF,SALARIO,NASCIMENTO,STATUS) VALUES ('ELIANE','251.654.889-74',15000,'2001-4-20','A');
INSERT INTO FUNCIONARIO (NOME,CPF,SALARIO,NASCIMENTO,STATUS) VALUES ('HORTÊNCIA','369.258.741-56',25700,'1980-7-30','T');

SELECT * FROM FUNCIONARIO;

SELECT 
	NOME
    ,SALARIO
    ,SALARIO * 0.1 AS 'BONUS'
    ,SALARIO * 0.05 AS 'DESCONTO'
    ,SALARIO + (SALARIO * 0.1) - (SALARIO * 0.05) AS 'TOTAL'
    ,CASE STATUS WHEN 'A' THEN 'ATIVO' WHEN 'I' THEN 'INATIVO' WHEN 'T' THEN 'TREINAMENTO' ELSE '' END AS 'STATUS'
    ,IF(SALARIO>20000,'GANHA MUITO',IF(SALARIO> 10000,'GANHA BEM','PRECISA DE AUMENTO'))
    ,SALARIO/3
    ,ROUND(SALARIO/3,2)
    ,TRUNCATE(SALARIO/3,2)
    ,DATE_FORMAT(NASCIMENTO,'%d/%m/%Y')
    ,TIMESTAMPDIFF(YEAR,NASCIMENTO,now())
FROM FUNCIONARIO;

SELECT MAX(SALARIO) FROM FUNCIONARIO;
SELECT MIN(SALARIO) FROM FUNCIONARIO;
SELECT AVG(SALARIO) FROM FUNCIONARIO;

